FROM ubuntu:16.04

RUN apt-get update
RUN apt-get install build-essential wget vim -y

RUN wget https://cache.ruby-lang.org/pub/ruby/2.6/ruby-2.6.0-preview1.tar.gz
RUN tar xzf ruby-2.6.0-preview1.tar.gz

RUN cd ruby-2.6.0-preview1 && ./configure && make && make install

# BUILD AND RUN
# docker build -t "ubuntu:ruby26" -f Dockerfile_ruby_2-6 .
# docker run -t -d ubuntu:ruby26
