FROM python:slim

# RUN pip install django

# ENV APP_HOME /django
# RUN mkdir -p $APP_HOME
# WORKDIR $APP_HOME

# RUN /bin/bash -l -c "django-admin startproject djangosite"
# BUILD AND RUN
# docker build -t "python:django" -f ./python/django/Dockerfile .
# docker run -t -d python:django
